platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven

inputs:
- name: hello-spring-boot

outputs:
- name: built-project

run:
  path: sh
  args:
  - -exc
  - |
    cd hello-spring-boot
    mvn package
    cp ./target/hello-spring-boot-0.0.1-SNAPSHOT.jar ../built-project/hello-spring-boot.jar
    cp manifest.yml ../built-project/manifest.yml